services:
  db:
    image: pgvector/pgvector:pg17   # trae PostgreSQL 17 + pgvector preinstalado
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chatbotia}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-masterylas20}
    ports:
      - "${POSTGRES_PORT:-25432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-chatbotia}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      args:
        # Pasar variables desde env.docker al Dockerfile durante el build
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
        POSTGRES_DB: ${POSTGRES_DB:-chatbotia}
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-masterylas20}
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        META_WHATSAPP_ACCESS_TOKEN: ${META_WHATSAPP_ACCESS_TOKEN:-}
        META_WHATSAPP_PHONE_NUMBER_ID: ${META_WHATSAPP_PHONE_NUMBER_ID:-}
        META_WHATSAPP_WEBHOOK_VERIFY_TOKEN: ${META_WHATSAPP_WEBHOOK_VERIFY_TOKEN:-my-secret-token}
        TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
        TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
        TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM:-whatsapp:+14155238886}
        WWEBJS_BASE_URL: ${WWEBJS_BASE_URL:-http://localhost:8085}
    ports:
      - "${APP_PORT:-8180}:8180"
    env_file:
      - env.docker
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
