server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
  application:
    name: chat.bot.ia
  jpa:
    properties:
      hibernate.default_schema: chatbotia
  datasource:
    url: jdbc:postgresql://localhost:25432/chatbotia
    username: postgres
    password: masterylas20
  ai:
    openai:
      api-key: sk-asdasdasdasdasd    # usa variable de entorno
      # opcional: el modelo por defecto
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 3072
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: chatbotia

logging:
  level:
    liquibase: DEBUG
    liquibase.lockservice: DEBUG
    liquibase.changelog: DEBUG

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

ai:
  base-url: http://localhost:8000

# Configuración del Chatbot
app:
  # Configuración de AI (Embeddings y Generación)
  ai:
    embeddings:
      provider: openai  # openai | http | mock
    
    openai:
      api-url: https://api.openai.com
      api-key: ${OPENAI_API_KEY:sk-test-key}
      timeout: 60
      
      embeddings:
        model: text-embedding-3-large  # text-embedding-3-large | text-embedding-3-small | text-embedding-ada-002
        dimensions: 3072               # 3072 para large, 1536 para small/ada
  
  # Configuración de WhatsApp
  whatsapp:
    provider: mock  # meta | twilio | mock
    
    meta:
      access-token: ${META_WHATSAPP_ACCESS_TOKEN:}
      phone-number-id: ${META_WHATSAPP_PHONE_NUMBER_ID:}
      webhook-verify-token: ${META_WHATSAPP_WEBHOOK_VERIFY_TOKEN:my-secret-token}
      api-version: ${META_WHATSAPP_API_VERSION:v21.0}
    
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      whatsapp-from: ${TWILIO_WHATSAPP_FROM:whatsapp:+14155238886}
  
  # Configuración de Knowledge Base
  knowledge-base:
    default-namespace: kb
    top-k-results: 5
    max-conversation-history: 10