
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/chatbotia
    username: postgres
    password: masterylas20
ai:
  base-url: http://localhost:8000

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: false