server:
  port: 8180
  servlet:
    context-path: /agent-ai-backend
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
  application:
    name: chat.bot.ia
  jpa:
    show-sql: false
    properties:
      hibernate.default_schema: chatbotia
      hibernate.format_sql: false   # formatea el SQL
      hibernate.highlight_sql: false
      hibernate.hbm2ddl.auto: validate  # Solo validar, no crear esquemas
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:25432}/${POSTGRES_DB:chatbotia}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:masterylas20}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      # opcional: el modelo por defecto
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        index-type: IVFFLAT
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: chatbotia

logging:
  level:
    liquibase: DEBUG
    liquibase.lockservice: DEBUG
    liquibase.changelog: DEBUG
    # SQL generado por Hibernate
    org.hibernate.SQL: error

    # Parámetros bind (Hibernate 6+)
    org.hibernate.orm.jdbc.bind: error
    org.hibernate.orm.jdbc.extract: error

    # (opcional) conexiones HikariCP
    com.zaxxer.hikari: INFO

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

ai:
  base-url: http://localhost:8000

# Configuración del Chatbot
app:
  # Configuración de AI (Embeddings y Generación)
  ai:
    embeddings:
      provider: openai  # openai | http | mock
    
    openai:
      api-url: https://api.openai.com
      api-key: ${OPENAI_API_KEY}
      timeout: 180
      max-buffer-size: 10485760  # 10MB - Límite del buffer para respuestas grandes (embeddings batch)
      
      # Configuración de Connection Pool
      connection:
        max-connections: 100              # Máximo número de conexiones simultáneas
        pending-acquire-timeout: 45       # Timeout en segundos para adquirir una conexión del pool
        max-idle-time: 20                 # Tiempo máximo en segundos que una conexión puede estar idle antes de cerrarse
        max-life-time: 60                 # Tiempo máximo de vida de una conexión en segundos
        eviction-interval: 30             # Intervalo en segundos para limpiar conexiones idle
      
      # Configuración de Retry Logic
      retry:
        max-attempts: 3                   # Número máximo de reintentos ante errores transitorios
        min-backoff: 1                    # Backoff inicial en segundos entre reintentos
        max-backoff: 10                   # Backoff máximo en segundos entre reintentos
      
      embeddings:
        model: text-embedding-3-small  # text-embedding-3-small | text-embedding-3-large | text-embedding-ada-002
        dimensions: 1536               # 1536 para small/ada, 3072 para large
  
  # Configuración de Vector Store
  vector-store:
    provider: pgvector  # pgvector | mock
  
  # Configuración de WhatsApp
  whatsapp:
    provider: wwebjs  # meta | twilio | mock | wwebjs
    
    meta:
      access-token: ${META_WHATSAPP_ACCESS_TOKEN:}
      phone-number-id: ${META_WHATSAPP_PHONE_NUMBER_ID:}
      webhook-verify-token: ${META_WHATSAPP_WEBHOOK_VERIFY_TOKEN:my-secret-token}
      api-version: ${META_WHATSAPP_API_VERSION:v21.0}
    
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
      whatsapp-from: ${TWILIO_WHATSAPP_FROM:whatsapp:+14155238886}
  
  # Configuración de Knowledge Base
  knowledge-base:
    default-namespace: kb
    top-k-results: 5
    max-conversation-history: 10

wwebjs:
  base-url: ${WWEBJS_BASE_URL:http://localhost:8085}
  send-text-path: /api/v1/messages/text
  send-template-path: /api/v1/messages/template
  connect-timeout-ms: 3000
  read-timeout-ms: 10000
