server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
  application:
    name: chat.bot.ia
  jpa:
    properties:
      hibernate.default_schema: chatbotia
  datasource:
    url: jdbc:postgresql://localhost:25432/chatbotia
    username: postgres
    password: masterylas20
  ai:
    openai:
      api-key: sk-asdasdasdasdasd    # usa variable de entorno
      # opcional: el modelo por defecto
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: chatbotia

logging:
  level:
    liquibase: DEBUG
    liquibase.lockservice: DEBUG
    liquibase.changelog: DEBUG

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

ai:
  base-url: http://localhost:8000